# 路徑生成基本設定
name: "default_path"            # 路徑名稱  
max_nodes: 20                    # 最大節點數
max_branches: 3                  # 每個節點最大分支數
max_height: 5                    # 最大層級數
special_node_probability: 0.2    # 特殊節點生成機率 (0.0-1.0)
map_name: "default_map"          # 地圖名稱

# 層級名稱設定
room_names:                     # 一般層級名稱
  - "survival_room"
  - "annihilation_room"
  - "defense_room"
  - "sniper_room"

boss_room_names:               # Boss層級名稱
  - "魔王關卡"
  - "Boss戰"
  - "最終Boss"
  - "終極Boss"
  - "傳說Boss"
  - "史詩Boss" 